USE DogsDB;

CREATE TABLE dogs (
    DOG_ID NUMBER(5) PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    BREED VARCHAR(20) NOT NULL,
    WEIGHT VARCHAR(5, 2) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    GENDER CHAR(1) NOT NULL,
    SPAYED_NEUTERED NUMBER(1) NOT NULL,
    STRANGER_FRIENDLY NUMBER(1) NOT NULL,
    LARGE_FRIENDLY NUMBER(1) NOT NULL,
    SMALL_FRIENDLY NUMBER(1) NOT NULL,
    PUPPY_FRIENDLY NUMBER(1) NOT NULL
);

CREATE TABLE dogs_allergys (
    DOG_ID NUMBER(5),
    ALLERGY VARCHAR(20),
    FOREIGN KEY(DOG_ID) REFERENCES dogs(DOG_ID)
);

CREATE TABLE dogs_vaccines (
    DOG_ID NUMBER(5),
    VACCINE VARCHAR(20),
    EXPIRATION_DATE DATE,
    FOREIGN KEY(DOG_ID) REFERENCES dogs(DOG_ID)
);